- SELECT SCORE.SNO  
        ,STUDENT.SNAME  
        ,SCORE.CNO  
        ,COURSE.CNAME 
        ,SCORE.RESULT
    FROM SCORE
    INNER JOIN STUDENT ON SCORE.SNO = STUDENT.SNO
    INNER JOIN COURSE ON SCORE.CNO = COURSE.CNO;
    
se