--프로그래머스 없어진 기록 찾기
--ANIMAL
SELECT ANIMAL_ID, NAME 
FROM ANIMAL_OUTS

MINUS

SELECT ANIMAL_ID, NAME 
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;


SELECT A.ANIMAL_ID, A.NAME 
FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL;


SELECT A.ANIMAL_ID, A.NAME 
FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.NAME IN ('Allie','Spice') AND B.ANIMAL_ID IS NULL;